version: '3.8'

volumes:
  pg_data:
      # driver: local
      external: true

services:
  postgres:
      image: postgres:latest
      volumes:
        - pg_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  pgadmin:
    image: dpage/pgadmin4:latest
  keycloak:
      # build: -t form-kc:1.0.0 .
      # build: .
      image: form-kc:1.0.1
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres